apiVersion: apps/v1
elastic-search:
  name: elasticsearch
  image:
    registry: docker.elastic.co/elasticsearch
    name: elasticsearch
    Tag: 7.16.2
  http-containerPort: 9200
  transport-containerPort: 9300
  resources:
    limits:
      cpu: "1"
      memory: 2Gi
    requests:
      cpu: "0.5"
      memory: 1Gi
  discover-type: "single-node"
  accessModes: "ReadWriteOnce"
  storage: 10Gi
  svc:
    apiVersion: v1

kibana:
  name: kibana
  image:
    registry: docker.elastic.co/kibana
    name: kibana
    Tag: 7.16.2
  http-containerPort: 5601
  ELASTICSEARCH_HOSTS: http://elasticsearch:9200
  storage: 10Gi
  svc:
    apiVersion: v1
    type: LoadBalancer