name: Delete Dependency
on:
  workflow_dispatch:
jobs:
  Deployment:
    name: Delete Dependency
    runs-on: self-hosted
    steps:
      - name: Remove github files
        run: |
          rm -rf ~/auto_deployment/