name: Deploy_Keda
on:
  workflow_dispatch:
    inputs:
      dockerimage:
        description: "Docker Image of your application"
        required: true
        type: string
      maxpods:
        description: "Maximum Number of pods to be deploy"
        required: true
        type: string
      minpods:
        description: "Minimum Number of pods to be deploy"
        required: true
        type: string
      metrics:
        description: "Metrics of KEDA"
        required: true
        type: string
      namespace:
        description: "Namespace of the application"
        required: true
        type: string
jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2
      - name: Set up kubeconfig
        run: |
          aws eks update-kubeconfig --region ${{ secrets.SHARED_EKS_REGION }} --name ${{ secrets.SHARED_EKS_NAME }}
      - name: Set up kubectl
        run: |
          ./automation-scripts/installation_scripts/installkubectl.sh
      - name: Install Helm
        run: |
          ./automation-scripts/installation_scripts/installhelm.sh
      - name: Install Keda
        run: |
          ./automation-scripts/installation_scripts/install_keda.sh
      - name: Clone github files to runner
        run: |
          ./automation-scripts/cloning_scripts/clonerepo.sh
      - name: Deploy the application with keda
        run: |
          ./automation-scripts/deployment_scripts/deploy_keda.sh --dockerimage ${{ inputs.dockerimage }} --maxpods ${{ inputs.maxpods }} --minpods ${{ inputs.minpods }} --metrics ${{ inputs.metrics }} --namespace ${{ inputs.namespace }}
      - name: Keda
        run: |
          output=$(./automation-scripts/output_scripts/getkeda.sh --namespace ${{ inputs.namespace }})
          echo "$output"
      - name: Domain
        run: |
          domain=$(./automation-scripts/output_scripts/getdomain.sh --namespace ${{ inputs.namespace }})
          echo "$domain"
      - name: Remove github files
        run: |
          rm -rf ~/auto_deployment/