name: Install Dependency for Keda
on:
  workflow_dispatch:
jobs:
  Deployment:
    name: Install Dependency
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2
      - name: Set up kubeconfig
        run: |
          aws eks update-kubeconfig --region ${{ secrets.SHARED_EKS_REGION }} --name ${{ secrets.SHARED_EKS_NAME }}
      - name: Set up kubectl
        run: |
          ./automation-scripts/installation_scripts/installkubectl.sh
      - name: Install Helm
        run: |
          ./automation-scripts/installation_scripts/installhelm.sh
      - name: Install Keda
        run: |
          ./automation-scripts/installation_scripts/install_keda.sh
      - name: Clone github files to runner
        run: |
          ./automation-scripts/cloning_scripts/clonerepo.sh