name: PrintIP
on:
  push:
    branches:
      - develop
  workflow_dispatch:
jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up SSH keys
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SHARED_EC2_PEM_KEY }}" > ~/.ssh/auto-deployment.pem
          chmod 600 ~/.ssh/auto-deployment.pem
      - name: Run script
        run: |
          ./automation-scripts/testin.sh