name: PrintIP
on:
  push:
    branches:
      - develop
  workflow_dispatch:
jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2
      - name: Install Helm
        run: |
          ./automation-scripts/installhelm.sh
      - name: Install Kubectl
        run: |
          ./automation-scripts/installkubectl.sh
      - uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.SHARED_EKS_KUBE_CONFIG }}
      - run: |
          ./automation-scripts/install_keda.sh
          
      
          
