name: PrintIP
on:
  push:
    branches:
      - develop
  workflow_dispatch:
jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run script
        run: |
          ./automation-scripts/testin.sh --sharedIP ${{ secrets.SHARED_EC2_IP }} --sharedName ${{ secrets.SHARED_EC2_IP }} > output.txt
      - name: Print output
        run: cat output.txt
