name: PrintIP
on:
  push:
    branches:
      - develop
  workflow_dispatch:
jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2
      - name: Set up kubeconfig
        run: |
          mkdir -p ~/.kube
          echo "$KUBECONFIG" | base64 -d > ~/.kube/config
        env:
          KUBECONFIG: ${{ secrets.SHARED_EKS_KUBE_CONFIG }}
      - name: Set up kubectl
        run: |
          ./automation-scripts/installkubectl.sh  
      - name: Install Helm
        run: |
          ./automation-scripts/installhelm.sh  
      - name: Install Keda
        run: |
          ./automation-scripts/install_keda.sh
      
          
