name: PrintIP
on:
  push:
    branches:
      - develop
  workflow_dispatch:
jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run script
        run: |
          sudo ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -i ${{ secrets.SHARED_EC2_PEM_KEY }}  ${{ secrets.SHARED_EC2_Name }}@${{ secrets.SHARED_EC2_IP }} "mkdir /home/ubuntu/ragav /home/ubuntu/shihaab /home/ubuntu/simaq"
